version: '3.7'
services:
  nginx:
    container_name: nginx-angular
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - "80:80"
      - "443:443"

# docker-compose -f docker-compose.prod.yml build
# docker-compose -f docker-compose.prod.yml up
